repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: https://github.com/typstyle-rs/pre-commit-typstyle
    rev: "v0.14.4"
    hooks:
      - id: typstyle
        args: ["--indent-width", "4", "-i", "."]
